---
- name: Build and Deploy todolist-fe 
  hosts: app
  vars:
    ci_cd_namespace: mak-ci-cd
    dev_namespace: mak-dev
    test_namespace: mak-test
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier
